MODE2_CSS = r'''
<style>
.st-key-final_upload_card,.st-key-final_conditions{min-height:450px;border:1px solid #d9e4f0;border-radius:11px;background:#fff;padding:16px 18px;gap:10px}
.st-key-final_upload_card [data-testid="stFileUploaderDropzoneInstructions"]>div:after{content:'검토 완료 Excel 파일(.xlsx) 1개를 업로드하세요.'}
.final-condition-title{display:flex;align-items:center;justify-content:flex-start;gap:8px;font-size:23px;font-weight:800;color:#10294d;border-bottom:1px solid #d9e4f0;padding-bottom:10px}.final-condition-title span{margin-left:auto;font-size:13px;font-weight:400;color:#617a99}
.st-key-final_conditions label p{font-size:15px;font-weight:650;color:#10294d}.st-key-final_conditions input{font-size:16px}
.final-recognized{display:flex;gap:20px;flex-wrap:wrap;font-size:14px;color:#617a99;padding:5px 0}.final-recognized b{color:#10294d;margin-left:8px}.final-filename{padding:9px 12px;border:1px solid #cde1ff;border-radius:8px;background:#eef6ff;color:#1677f2;overflow-wrap:anywhere}.final-filename small{display:block;color:#617a99;font-size:12px}.final-filename b{font-size:15px;display:block;margin-top:3px}
.st-key-final_steps{border:1px solid #d9e4f0;border-radius:11px;background:#fff;padding:14px 16px;gap:12px}.final-stage-header{display:flex;justify-content:space-between;align-items:center;gap:16px}.final-stage-header .panel-title{font-size:25px;display:flex;align-items:center;gap:14px}.final-pin{display:inline-block;width:28px;height:28px;border-radius:50% 50% 50% 0;background:#1677f2;transform:rotate(-45deg);position:relative}.final-pin:after{content:"";position:absolute;width:10px;height:10px;background:#fff;border-radius:50%;left:9px;top:9px}.final-stage-header .panel-desc{font-size:14px}.final-status{background:#eef8f3;border:1px solid #ccebdc;border-radius:9px;padding:10px 16px;min-width:290px;color:#079653}.final-status.attention{background:#fff2f3;border-color:#ffc9ce;color:#ef3038}.final-status b{display:block;font-size:21px}.final-status small{display:block;font-size:12px;color:#617a99}
.st-key-final_check_step,.st-key-final_generate_step,.st-key-final_download_step{border-radius:10px;padding:12px 14px;gap:10px;min-height:234px}.st-key-final_check_step{border:1px solid #bedcff;background:linear-gradient(120deg,#f2f8ff,#fbfdff)}.st-key-final_generate_step{border:1px solid #c6ead7;background:linear-gradient(120deg,#f0faf6,#fbfefd)}.st-key-final_download_step{border:1px solid #ffd8b9;background:linear-gradient(120deg,#fff8f2,#fffcfa)}
.final-step-heading{display:flex;align-items:center;gap:12px;color:#1677f2;white-space:nowrap}.final-step-heading span{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:#1677f2;color:#fff;font-size:23px;flex-shrink:0}.final-step-heading b{font-size:21px}.final-step-heading.green{color:#079653}.final-step-heading.green span{background:#0aa35e}.final-step-heading.orange{color:#f97316}.final-step-heading.orange span{background:#f97316}.final-step-desc{font-size:14px;line-height:1.55;color:#496789;min-height:54px;margin-top:8px;padding-bottom:6px}
.st-key-final_steps div.stButton>button,.st-key-final_steps div.stDownloadButton>button{min-height:49px;width:100%;color:#fff;border:0;font-size:16px;font-weight:750}.st-key-final_check_step div.stButton>button{background:#1677f2;border-color:#1677f2}.st-key-final_generate button{background:#0aa35e}.st-key-final_download_step div.stDownloadButton>button{background:#ff7418;border-color:#ff7418}
.st-key-final_steps button p{font-size:17px;font-weight:750}.st-key-final_check button:disabled,.st-key-final_generate button:disabled,.st-key-final_halfyear_download button:disabled{opacity:.45;color:#fff}
.final-count{padding:8px 10px;border:1px solid;border-radius:8px;font-size:14px}.final-count b,.final-count small{display:block}.final-count small{font-size:12px;color:#617a99;margin-top:3px}.final-count.blue{background:#eef6ff;border-color:#cee3ff;color:#1677f2}.final-count.green{background:#effaf5;border-color:#ccebdc;color:#079653}.final-count.orange{background:#fff6ef;border-color:#ffdabe;color:#d9600c}
.final-workflow{display:flex;flex-wrap:wrap;align-items:center;gap:12px;background:#eef6ff;border:1px solid #cde1ff;border-radius:9px;padding:11px 14px;color:#1677f2;font-size:14px}.final-workflow b{font-size:17px}.final-workflow details{margin-left:auto;font-size:13px}.final-workflow summary{cursor:pointer}.final-workflow details[open]{flex-basis:100%;line-height:1.7}
.final-sheets,.final-result-summary{display:flex;flex-wrap:wrap;align-items:center;gap:14px;border:1px solid #d9e4f0;border-radius:10px;background:#fff;padding:12px 16px;color:#10294d;font-size:15px}.final-sheets span{flex:1;min-width:115px;padding:10px 14px;border:1px solid #cde1ff;background:#f6faff;border-radius:8px;color:#1677f2;font-weight:700}.final-sheets span:nth-of-type(2){border-color:#c6ead7;color:#079653;background:#f2faf6}.final-sheets span:nth-of-type(3){border-color:#ffd8b9;color:#f97316;background:#fff8f2}.final-sheets span:nth-of-type(4){color:#496789}.final-result-summary span{font-size:14px;color:#496789}
@media(max-width:1250px){.final-stage-header{align-items:flex-start;flex-direction:column}.final-step-heading{gap:7px;white-space:normal}.final-step-heading b{font-size:18px}.final-step-heading span{width:32px;height:32px}.st-key-final_check_step,.st-key-final_generate_step,.st-key-final_download_step{padding:10px}.final-step-desc{min-height:65px}.final-condition-title{font-size:20px}.final-condition-title span{font-size:12px}}
@media(max-width:1000px){[data-testid="stHorizontalBlock"]:has(>.stColumn .st-key-final_upload_card),[data-testid="stHorizontalBlock"]:has(>.stColumn .st-key-final_check_step){flex-direction:column}[data-testid="stHorizontalBlock"]:has(.st-key-final_upload_card)>[data-testid="stColumn"],[data-testid="stHorizontalBlock"]:has(.st-key-final_check_step)>[data-testid="stColumn"]{width:100%;flex:1 1 100%}.st-key-final_upload_card,.st-key-final_conditions{min-height:0}.final-step-desc{min-height:0}.st-key-final_check_step,.st-key-final_generate_step,.st-key-final_download_step{min-height:0}}
.final-auto-status{min-height:49px;display:flex;align-items:center;color:#067a43;font-size:18px;font-weight:750;padding:0 10px}
.st-key-final_sheet_preview{background:#fff;border:1px solid #d9e4f0;border-radius:10px;padding:16px}
.st-key-final_sheet_preview h3{font-size:21px;color:#10294d}
.st-key-final_preview_sheet [role="radiogroup"]{gap:12px;flex-wrap:wrap}
.st-key-final_preview_sheet [role="radiogroup"] label{border:1px solid #bedcff;border-radius:8px;background:#f4f9ff;padding:10px 18px;cursor:pointer}
.st-key-final_preview_sheet [role="radiogroup"] label:has(input:checked){background:#e0eeff;border:2px solid #1677f2}
.st-key-final_preview_sheet [role="radiogroup"] label p{font-size:17px;font-weight:700;color:#10294d}
</style>
'''
