APP_CSS = r"""
<style>
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css');
:root{--blue:#2563EB;--blue2:#1D4ED8;--soft:#EFF6FF;--ink:#172033;--muted:#667085;--bg:#F7F9FC;--line:#E4EAF2;--green:#16A36A;--greens:#ECFDF3;--amber:#D97706;--ambers:#FFF8E7;--card:#FFFFFF}
html,body,[class*="css"]{font-family:'Pretendard',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}#MainMenu,footer,header{visibility:hidden}.stApp{background:var(--bg)}.block-container{max-width:1240px;padding-top:1.7rem;padding-bottom:3rem}
[data-testid="stSidebar"]{background:#FBFCFE!important;border-right:1px solid var(--line)}[data-testid="stSidebar"] *{letter-spacing:-.01em}[data-testid="stSidebar"] h1,[data-testid="stSidebar"] h2,[data-testid="stSidebar"] h3{color:var(--ink)!important}[data-testid="stSidebar"] label,[data-testid="stSidebar"] p,[data-testid="stSidebar"] .stCaption{color:#475467!important}[data-testid="stSidebar"] hr{border-color:var(--line)}
[data-testid="stSidebar"] [data-testid="stFileUploaderDropzone"],[data-testid="stSidebar"] [data-testid="stFileUploadDropzone"],[data-testid="stFileUploaderDropzone"],[data-testid="stFileUploadDropzone"]{background:#fff!important;border:1px dashed #B8C7DD!important;border-radius:12px!important}[data-testid="stFileUploaderDropzone"] *,[data-testid="stFileUploadDropzone"] *{color:#344054!important;fill:#344054!important}
/* Streamlit 버튼 안쪽 글자가 테마에 덮이지 않도록 모든 자식까지 명시 */
div.stButton>button{background:var(--blue)!important;color:#fff!important;border:1px solid var(--blue)!important;border-radius:9px!important;min-height:42px;font-weight:700!important;transition:.15s ease}div.stButton>button *,div.stButton>button p,div.stButton>button span{color:#fff!important}div.stButton>button:hover{background:var(--blue2)!important;border-color:var(--blue2)!important;transform:translateY(-1px)}
div.stDownloadButton>button{background:var(--blue)!important;color:#fff!important;border:1px solid var(--blue)!important;border-radius:9px!important;min-height:42px;font-weight:700!important;width:100%}div.stDownloadButton>button *,div.stDownloadButton>button p,div.stDownloadButton>button span{color:#fff!important}div.stDownloadButton>button:hover{background:var(--blue2)!important;border-color:var(--blue2)!important}
/* A안: 미니멀 업무앱형 */
.app-head{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-bottom:18px;padding-bottom:16px;border-bottom:1px solid var(--line)}.app-brand{display:flex;gap:12px;align-items:center}.app-logo{width:42px;height:42px;border-radius:11px;background:linear-gradient(135deg,#2F6FED,#5B8DF6);display:flex;align-items:center;justify-content:center;color:#fff;font-size:20px;box-shadow:0 5px 14px rgba(37,99,235,.18)}.app-title{font-size:1.45rem;font-weight:800;color:var(--ink);letter-spacing:-.035em}.app-sub{font-size:.84rem;color:var(--muted);margin-top:3px}.live-chip{background:#fff;border:1px solid var(--line);border-radius:999px;padding:7px 11px;font-size:.76rem;color:#475467;white-space:nowrap}
.mode-switch{margin-bottom:16px}.section-title{font-size:.94rem;font-weight:800;color:var(--ink);margin:22px 0 10px}.card-title{font-size:.96rem;font-weight:800;color:var(--ink);margin-bottom:4px}.card-desc{font-size:.78rem;color:var(--muted);line-height:1.5;margin-bottom:12px}.card-icon{width:40px;height:40px;border-radius:50%;display:flex;align-items:center;justify-content:center;background:var(--soft);font-size:20px;margin-bottom:10px}.card-icon.green{background:var(--greens)}
[data-testid="stVerticalBlockBorderWrapper"]{border-color:var(--line)!important;border-radius:13px!important;background:#fff!important;box-shadow:0 1px 2px rgba(16,24,40,.025)}
.kpi-row{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:16px}.kpi-card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:16px 17px;box-shadow:0 1px 2px rgba(16,24,40,.025)}.kpi-label{font-size:.76rem;color:var(--muted);font-weight:650;margin-bottom:6px}.kpi-value{font-size:1.48rem;font-weight:800;color:var(--ink);letter-spacing:-.035em}.kpi-unit{font-size:.82rem;color:var(--muted);font-weight:600;margin-left:3px}.kpi-note{font-size:.73rem;color:var(--muted);margin-top:5px}.small-value{font-size:1.02rem!important;padding-top:6px}
.work-card,.download-card,.mode-banner,.empty-card,.info-panel,.region-card{background:#fff;border:1px solid var(--line);border-radius:13px}.work-card{padding:17px 19px;margin-bottom:15px}.work-title{font-size:.93rem;font-weight:800;color:var(--ink);margin-bottom:5px}.work-desc{font-size:.8rem;color:var(--muted);line-height:1.55}.status{display:inline-flex;align-items:center;border-radius:999px;padding:5px 10px;font-size:.75rem;font-weight:750}.status.ok{background:var(--greens);color:var(--green)}.status.warn{background:var(--ambers);color:var(--amber)}
.download-card{display:flex;gap:12px;align-items:flex-start;padding:17px 18px;margin-bottom:10px;min-height:94px}.download-icon{width:42px;height:42px;flex:0 0 42px;border-radius:50%;background:var(--soft);display:flex;align-items:center;justify-content:center;font-size:20px}.final-card{margin-top:15px}.mode-banner{padding:20px 22px;margin-bottom:16px}.mode-eyebrow{font-size:.73rem;color:var(--blue);font-weight:800;margin-bottom:4px}.mode-title{font-size:1.12rem;color:var(--ink);font-weight:800}.mode-desc{font-size:.8rem;color:var(--muted);margin-top:5px}.info-panel{display:flex;gap:11px;padding:17px 18px;min-height:115px}.info-icon{width:34px;height:34px;flex:0 0 34px;border-radius:50%;background:var(--greens);color:var(--green);display:flex;align-items:center;justify-content:center;font-weight:800}.empty-card{text-align:center;padding:38px 20px;margin-top:15px}.empty-icon{font-size:1.7rem;margin-bottom:8px}
.region-card{padding:16px 18px;margin-top:14px}.region-track{height:8px;background:#EEF2F7;border-radius:999px;overflow:hidden;display:flex;margin:10px 0 8px}.region-seg-1{background:#2563EB}.region-seg-2{background:#14B8A6}.region-seg-3{background:#CBD5E1}.region-legend{display:flex;gap:18px;flex-wrap:wrap;font-size:.75rem;color:var(--muted)}.side-section{font-size:.78rem;font-weight:800;color:#344054;margin:2px 0 8px}.side-help{font-size:.72rem;color:#667085;line-height:1.5;margin-top:5px}.waiting-card{max-width:480px;margin:80px auto;background:#fff;border:1px solid var(--line);border-radius:16px;text-align:center;padding:36px}.waiting-icon{font-size:2rem}.waiting-title{font-size:1.05rem;font-weight:800;color:var(--ink);margin:10px 0 5px}.waiting-desc{font-size:.84rem;color:var(--muted)}.waiting-meta{font-size:.74rem;color:#98A2B3;margin-top:12px}
@media(max-width:900px){.kpi-row{grid-template-columns:1fr 1fr}.app-head{align-items:flex-start}.live-chip{margin-top:2px}}@media(max-width:640px){.kpi-row{grid-template-columns:1fr}.app-head{display:block}.live-chip{display:inline-block;margin-top:10px}}
</style>
"""
