APP_CSS = r"""
<style>
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.css');
:root{--bg:#f8fbff;--navy:#10294b;--text:#28486e;--muted:#6b7f98;--line:#d8e4f1;--blue:#1677f2;--blue2:#0a66d8;--green:#0aa35e;--orange:#f97316;--red:#ef3038}
html,body,[class*="css"]{font-family:'Pretendard',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:-.015em}
#MainMenu,footer{visibility:hidden!important}
header[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],[data-testid="stStatusWidget"]{display:none!important;visibility:hidden!important;height:0!important}
[data-testid="stSidebarCollapseButton"],[data-testid="stSidebar"] [data-testid="baseButton-header"],[data-testid="stSidebar"] button[kind="header"],[data-testid="stSidebarCollapsedControl"],[data-testid="collapsedControl"]{display:none!important;visibility:hidden!important}
.stApp{background:linear-gradient(180deg,#ffffff 0%,#f8fbff 100%);color:var(--navy)}
.block-container{max-width:1580px;padding:1rem 1.4rem 1.7rem!important}
[data-testid="stSidebar"]{background:#f8fafc!important;border-right:1px solid var(--line);min-width:288px!important;max-width:305px!important}
[data-testid="stSidebar"]>div:first-child{padding-top:1rem!important;padding-left:.9rem!important;padding-right:.9rem!important}
[data-testid="stSidebar"] label,[data-testid="stSidebar"] p,[data-testid="stSidebar"] .stCaption{color:#52637a!important;font-size:.82rem!important}
[data-testid="stSidebar"] hr{border-color:var(--line);margin:.7rem 0!important}
.sidebar-brand{font-size:1rem;font-weight:800;color:var(--navy);margin:2px 0 11px}.side-section{font-size:.7rem;font-weight:750;color:#718198;text-transform:uppercase;letter-spacing:.055em;margin:4px 0 6px}.developer-note{font-size:.73rem;line-height:1.45;color:#718198;background:#fff;border:1px solid var(--line);border-radius:8px;padding:9px 10px;margin:7px 0 3px}.developer-note b{color:#43546b}

/* approved standard hero */
.standard-hero{display:flex;align-items:center;justify-content:space-between;gap:20px;margin:0 0 16px}.hero-left{display:flex;align-items:center;gap:16px}.hero-building{width:54px;height:54px;display:flex;align-items:center;justify-content:center;color:#123e74;font-size:2.25rem;font-weight:900;line-height:1}.hero-title{font-size:1.72rem;line-height:1.15;font-weight:900;color:#10294b;letter-spacing:-.045em}.hero-sub{font-size:.92rem;color:#496789;margin-top:5px}.hero-info{display:flex;align-items:center;gap:10px;max-width:430px;background:#f3f8ff;border:1px solid #bcd8ff;border-radius:10px;padding:12px 16px;color:#1764ba;font-size:.79rem;font-weight:650}.hero-info>span{display:inline-flex;width:22px;height:22px;border-radius:50%;align-items:center;justify-content:center;background:#1677f2;color:#fff;font-size:.72rem;font-weight:800;flex:0 0 22px}.hero-info small{display:block;color:#86a0bd;font-size:.64rem;font-weight:500;margin-top:2px}

/* cards */
[data-testid="stVerticalBlockBorderWrapper"]{border-color:var(--line)!important;border-radius:11px!important;background:#fff!important;box-shadow:0 2px 8px rgba(44,86,133,.045)!important}
[data-testid="stVerticalBlockBorderWrapper"]>div{padding:.85rem 1rem!important}
.st-key-upload_card [data-testid="stVerticalBlockBorderWrapper"],.st-key-filter_card [data-testid="stVerticalBlockBorderWrapper"]{min-height:458px}
.panel-head{display:flex;gap:13px;align-items:center;margin-bottom:9px}.panel-icon{width:44px;height:44px;border-radius:6px;display:flex;align-items:center;justify-content:center;color:#fff;font-size:1.55rem;font-weight:900}.blue-icon{background:linear-gradient(180deg,#2b86ff,#0f70eb)}.panel-title{font-size:1.38rem;font-weight:900;color:var(--navy);line-height:1.1}.panel-desc{font-size:.82rem;color:#4d6989;margin-top:5px}.panel-desc b{font-weight:650}

/* uploader */
[data-testid="stFileUploaderDropzone"],[data-testid="stFileUploadDropzone"]{background:#fcfdff!important;border:1.5px dashed #bfd0e3!important;border-radius:9px!important;min-height:168px!important;padding:1.2rem!important;display:flex!important;align-items:center!important;justify-content:center!important}
[data-testid="stFileUploaderDropzone"] *,[data-testid="stFileUploadDropzone"] *{color:#24466f!important;fill:#1677f2!important}
[data-testid="stFileUploaderDropzone"] button,[data-testid="stFileUploadDropzone"] button{background:#fff!important;border:1px solid #cdd8e5!important;color:#163a63!important;border-radius:8px!important;font-weight:750!important}
.drop-guide{text-align:center;margin-top:-120px;pointer-events:none;position:relative;z-index:1;color:#143b6b;font-size:.8rem}.drop-guide .drop-cloud{font-size:2rem;color:#1677f2;line-height:1;margin-bottom:7px}.drop-guide b{display:block;font-size:.86rem}.drop-guide span{display:block;font-size:.72rem;color:#677f9b;margin-top:5px}.source-path-guide{margin-top:72px;padding:10px 13px;background:#f3f8ff;border:1px solid #c9ddf8;border-radius:8px;font-size:.75rem;line-height:1.55;color:#3e6086}.source-path-guide b{color:#0d6cda}.source-path-guide small{color:#6f8298}.path-info{display:inline-flex;width:18px;height:18px;border-radius:50%;align-items:center;justify-content:center;background:#1677f2;color:#fff;font-size:.55rem;margin-right:4px}.upload-checks{display:flex;flex-direction:column;gap:4px;margin-top:10px;font-size:.72rem;color:#52708f}.upload-checks span::first-letter{color:#1677f2}

/* filter card */
.filter-title-row{display:flex;align-items:center;gap:8px;padding-bottom:10px;margin-bottom:10px;border-bottom:1px solid #e2eaf4}.filter-icon{font-size:1.35rem;color:#153d70;font-weight:900}.filter-title{font-size:1.16rem;font-weight:900;color:var(--navy)}.filter-title span{font-size:.72rem;font-weight:700}.filter-note{font-size:.7rem;color:#70849b;margin-left:auto}.field-title{font-size:.88rem;font-weight:850;color:#183657;margin:4px 0 6px}.field-title>span:not(.field-info){font-size:.7rem;color:#6f8298;font-weight:650}.field-info{display:inline-flex;width:17px;height:17px;align-items:center;justify-content:center;border-radius:50%;background:#91a2b8;color:#fff;font-size:.62rem;margin-left:4px}
.st-key-filter_card [role="radiogroup"]{gap:18px!important;margin-bottom:4px}.st-key-filter_card [role="radiogroup"] label{font-size:.8rem!important;font-weight:650!important;color:#294868!important}.auto-region-box{padding:9px 11px;background:#f2f7fd;border:1px solid #d0e0f1;border-radius:7px;margin:5px 0 9px}.auto-region-box span{font-size:.7rem;color:#617894;margin-right:8px}.auto-region-box b{font-size:.9rem;color:#086cd7;margin-right:6px}.auto-region-box small{display:block;color:#72869d;font-size:.65rem;margin-top:3px}.filter-divider{height:1px;background:#e5edf5;margin:10px -1rem 10px}.direct-input-label{font-size:.65rem;color:#637a94;margin-bottom:2px;text-align:left}
.st-key-filter_card [data-testid="stNumberInput"] input,.st-key-filter_card [data-baseweb="select"]>div{min-height:39px!important;border-radius:8px!important;border-color:#cdd9e6!important;font-size:.78rem!important}.st-key-filter_card [data-testid="stSlider"]{margin-top:8px}.slider-caption{display:flex;align-items:center;justify-content:space-between;font-size:.66rem;color:#6f839a;margin-top:-5px}.slider-caption b{color:#0a6bd7;font-size:.7rem}

/* general buttons */
div.stButton>button,div.stDownloadButton>button{border-radius:8px!important;min-height:40px!important;font-weight:780!important;font-size:.82rem!important;box-shadow:none!important;transition:.12s ease}.st-key-filter_card div.stButton>button{min-height:40px!important;background:#fff!important;color:#193d66!important;border:1px solid #ccd9e7!important}.st-key-filter_card div.stButton>button[kind="primary"]{background:#1677f2!important;color:#fff!important;border-color:#1677f2!important}.st-key-filter_card div.stButton>button[kind="primary"] *{color:#fff!important}.st-key-filter_card div.stButton>button:hover{transform:none!important;box-shadow:0 2px 6px rgba(22,119,242,.08)!important}
div.stButton>button[kind="primary"],div.stDownloadButton>button{background:#1677f2!important;color:#fff!important;border:1px solid #1677f2!important}div.stButton>button[kind="secondary"]{background:#fff!important;color:#203a5d!important;border:1px solid #cfdbea!important}

/* address header */
.address-head-row{display:flex;justify-content:space-between;align-items:center;gap:14px;margin:18px 0 10px;padding:0 3px}.address-head-left{display:flex;align-items:center;gap:12px}.address-pin{width:42px;height:42px;border-radius:50% 50% 50% 0;background:linear-gradient(180deg,#2c89ff,#0d6fec);transform:rotate(-45deg);color:transparent;position:relative;flex:0 0 42px}.address-pin:after{content:"";position:absolute;width:13px;height:13px;border-radius:50%;background:#fff;left:14px;top:14px}.address-title{font-size:1.45rem;font-weight:900;color:var(--navy);letter-spacing:-.04em}.address-sub{font-size:.78rem;color:#56718f;margin-top:3px}.address-missing-card,.address-complete-card{display:flex;align-items:center;gap:11px;min-width:390px;padding:12px 18px;border-radius:10px}.address-missing-card{background:#fff2f3;border:1px solid #ffc9cd;color:#ed2d36}.address-complete-card{background:#f0fbf6;border:1px solid #c8edd9;color:#079657}.status-icon{font-size:1.75rem}.address-missing-card b,.address-complete-card b{display:block;font-size:1.34rem;line-height:1.1}.address-missing-card span,.address-complete-card span{font-size:.69rem;color:#5f7590;display:block;margin-top:4px}

/* 3 step cards */
.st-key-api_address_card [data-testid="stVerticalBlockBorderWrapper"]{border-color:#bfdcff!important;background:linear-gradient(180deg,#fff,#f9fcff)!important}.st-key-user_address_card [data-testid="stVerticalBlockBorderWrapper"]{border-color:#c8e9d8!important;background:linear-gradient(180deg,#fff,#fbfffd)!important}.st-key-manual_address_card [data-testid="stVerticalBlockBorderWrapper"]{border-color:#ffd8bb!important;background:linear-gradient(180deg,#fff,#fffdfb)!important}.st-key-api_address_card [data-testid="stVerticalBlockBorderWrapper"],.st-key-user_address_card [data-testid="stVerticalBlockBorderWrapper"],.st-key-manual_address_card [data-testid="stVerticalBlockBorderWrapper"]{min-height:252px}
.step-card-title{font-size:1.18rem;font-weight:900;margin-bottom:9px}.step-card-title span{display:inline-flex;width:34px;height:34px;align-items:center;justify-content:center;border-radius:50%;color:#fff;margin-right:7px;font-size:.9rem}.step-card-title.blue{color:#0870df}.step-card-title.blue span{background:#1677f2}.step-card-title.green{color:#079653}.step-card-title.green span{background:#0aa35e}.step-card-title.orange{color:#ef6a08}.step-card-title.orange span{background:#f97316}.step-card-desc{min-height:55px;font-size:.74rem;line-height:1.5;color:#506c8c;margin-bottom:8px}
.st-key-api_fill_button button{background:#1677f2!important;color:#fff!important;border-color:#1677f2!important}.st-key-bulk_user_address_button button{background:#0aa35e!important;color:#fff!important;border-color:#0aa35e!important}.st-key-open_manual_button button{background:#f97316!important;color:#fff!important;border-color:#f97316!important}.st-key-api_fill_button button *,.st-key-bulk_user_address_button button *,.st-key-open_manual_button button *{color:#fff!important}.st-key-bulk_user_address_button button:disabled{background:#a8d9c2!important;border-color:#a8d9c2!important;color:#fff!important;opacity:1!important}
.step-count{display:flex;align-items:center;gap:10px;padding:9px 11px;border-radius:8px;margin-top:8px}.step-count .count-icon{width:30px;height:30px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:.9rem}.step-count b{display:block;font-size:.77rem}.step-count small{display:block;font-size:.64rem;color:#62778e;margin-top:2px}.blue-count{background:#f2f8ff;border:1px solid #cfe3ff;color:#116bc8}.blue-count .count-icon{background:#dfeeff;color:#1677f2}.green-count{background:#f0fbf6;border:1px solid #ccebdc;color:#087f4b}.green-count .count-icon{background:#ddf4e8;color:#0aa35e}.orange-count{background:#fff7ef;border:1px solid #ffdabe;color:#d95d07}.orange-count .count-icon{background:#ffead8;color:#f97316}

/* workflow */
.workflow-strip{display:flex;align-items:center;gap:13px;flex-wrap:wrap;margin:12px 0 10px;padding:10px 14px;background:#f1f7ff;border:1px solid #b9d7ff;border-radius:9px;color:#126ac9;font-size:.72rem;font-weight:750}.workflow-label{display:flex;align-items:center;gap:7px;margin-right:5px}.workflow-label>span{display:inline-flex;width:22px;height:22px;align-items:center;justify-content:center;border-radius:50%;background:#1677f2;color:#fff}.workflow-step{display:inline-flex;align-items:center;gap:6px}.workflow-step em{font-style:normal;display:inline-flex;width:25px;height:25px;align-items:center;justify-content:center;border-radius:50%;background:#1677f2;color:#fff;font-size:.7rem}.workflow-strip>i{font-style:normal;color:#809bb8;font-size:1rem}

/* existing output and mode2 compatibility */
.app-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin:0 0 16px;padding:0 0 15px;border-bottom:1px solid var(--line)}.app-brand{display:flex;gap:11px;align-items:center}.app-logo{width:38px;height:38px;border-radius:9px;background:#0f2747;display:flex;align-items:center;justify-content:center;color:#fff;font-size:17px;font-weight:800}.app-title{font-size:1.35rem;font-weight:800;color:#10294b}.app-sub{font-size:.79rem;color:#60728c;margin-top:2px}.live-chip{background:#eef6ff;border:1px solid #cfe3ff;border-radius:9px;padding:7px 11px;font-size:.73rem;color:#1769c2;white-space:nowrap}
.section-title{font-size:1rem;font-weight:800;color:#10294b;margin:15px 0 8px}.section-title:after{content:"";display:inline-block;width:4px;height:4px;background:#8ca0b8;border-radius:50%;margin:0 0 2px 7px}.compact-title{margin-top:11px!important}.card-title{font-size:.9rem;font-weight:750;color:#183354}.card-desc{font-size:.76rem;color:#6b7e95;line-height:1.45}.work-card,.download-card,.mode-banner,.empty-card,.info-panel,.region-card{background:#fff;border:1px solid var(--line);border-radius:9px}.work-card{padding:12px 13px;margin-bottom:9px}.work-title{font-size:.87rem;font-weight:700;color:#183354}.work-desc{font-size:.75rem;color:#6b7e95;line-height:1.5}.download-card{display:flex;gap:9px;align-items:flex-start;padding:11px 12px;margin-bottom:6px;min-height:66px}.download-icon{width:32px;height:32px;flex:0 0 32px;border-radius:7px;background:#eef6ff;display:flex;align-items:center;justify-content:center;color:#1677f2}.info-panel{display:flex;gap:9px;padding:11px 12px;min-height:74px}.info-icon{width:29px;height:29px;flex:0 0 29px;border-radius:7px;background:#eef6ff;color:#1677f2;display:flex;align-items:center;justify-content:center;font-weight:700}.mode-banner{padding:12px 14px;margin-bottom:10px}.mode-eyebrow{font-size:.69rem;color:#718198;font-weight:700}.mode-title{font-size:1rem;color:#183354;font-weight:750}.mode-desc{font-size:.75rem;color:#718198;margin-top:3px}.region-card{padding:12px 14px;margin-top:9px}.region-track{height:7px;background:#edf2f7;border-radius:999px;overflow:hidden;display:flex;margin:9px 0}.region-seg-1{background:#1677f2}.region-seg-2{background:#7aaeea}.region-seg-3{background:#d5e5f7}.region-legend{display:flex;gap:16px;flex-wrap:wrap;font-size:.71rem;color:#718198}.kpi-row{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin:9px 0 12px}.kpi-card{background:#fff;border:1px solid var(--line);border-radius:8px;padding:13px 14px}.kpi-label{font-size:.71rem;color:#71717a;font-weight:600}.kpi-value{font-size:1.5rem;font-weight:750;color:#10294b}.kpi-unit{font-size:.75rem;color:#71717a;margin-left:2px}.kpi-note{font-size:.7rem;color:#8d9aad;margin-top:5px}
.waiting-card{max-width:460px;margin:60px auto;background:#fff;border:1px solid var(--line);border-radius:11px;text-align:center;padding:28px}.waiting-title{font-size:1rem;font-weight:750;color:#183354;margin:7px 0 4px}.waiting-desc,.waiting-meta{font-size:.76rem;color:#718198}
[data-testid="stAlert"]{padding:.58rem .72rem!important;font-size:.77rem!important;margin:.35rem 0!important;border-radius:8px!important}[data-testid="stDataFrame"],[data-testid="stDataEditor"]{font-size:.76rem!important;border:1px solid var(--line)!important;border-radius:9px!important;overflow:hidden!important}[data-testid="stExpander"]{border:1px solid var(--line)!important;border-radius:10px!important;background:#fff!important}
@media(max-width:1180px){.standard-hero{align-items:flex-start;flex-direction:column}.hero-info{max-width:none}.address-head-row{align-items:stretch;flex-direction:column}.address-missing-card,.address-complete-card{min-width:0}.st-key-upload_card [data-testid="stVerticalBlockBorderWrapper"],.st-key-filter_card [data-testid="stVerticalBlockBorderWrapper"]{min-height:0}}
@media(max-width:760px){.block-container{padding-left:.8rem!important;padding-right:.8rem!important}.hero-title{font-size:1.35rem}.hero-building{width:42px;height:42px;font-size:1.8rem}.workflow-strip{display:block}.workflow-step{margin:4px 6px 4px 0}.filter-note{display:none}}
</style>
"""
