[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1677F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F7FC"
textColor = "#10294D"
font = "sans serif"
